// 友链检测 CLI 需要使用显式导入和相对路径
import type { FeedGroup } from "../app/types/feed";
import { myFeed } from "../blog.config";
// eslint-disable-next-line unused-imports/no-unused-imports
import {
	getFavicon,
	getGithubAvatar,
	getGithubIcon,
	getOciqGroupAvatar,
	getOicqAvatar,
	OicqAvatarSize,
} from "./utils/img";

export default [
	// #region Clarity
	{
		name: "清晰体验",
		desc: "使用 Clarity 博客主题构建的网站。",
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: "GuuGuai",
				sitenick: "杂记本",
				title: "古怪杂记本",
				desc: "一个什么都可能会写的博客",
				link: "https://blog.guuguai.site/",
				feed: "https://blog.guuguai.site/atom.xml",
				icon: "https://cravatar.cn/avatar/646331BFF8F19A0E05679C3CC0FC54D6",
				avatar:
					"https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160",
				archs: ["Nuxt", "Netlify"],
				date: "2023-12-23",
				comment: "高中同学，技术好友，爱好番剧/折腾。",
			},
			{
				author: "Xlenco",
				sitenick: "希乐博客",
				desc: "互联网中的静谧之地",
				link: "https://blog.xlenco.top/",
				feed: "https://blog.xlenco.top/atom.xml",
				icon: "https://weavatar.com/avatar/67254b346498965226e5c91ebff66a69570b97f224d2d061e504b4eade1f00fa",
				avatar: getOicqAvatar("1043865083"),
				archs: ["Nuxt", "EdgeOne"],
				date: "2024-07-28",
				comment: "学生，经验分享。",
			},
			{
				author: "梦爱吃鱼",
				desc: "不负心灵，不负今生。",
				link: "https://blog.bsgun.cn/",
				feed: "https://blog.bsgun.cn/atom.xml",
				icon: "https://bsgun.cn/favicon.ico",
				avatar: "https://oss-cdn.bsgun.cn/logo/avatar.256.png",
				archs: ["Nuxt", "EdgeOne"],
				date: "2024-08-20",
				comment: "博客折腾",
			},
			{
				author: "鹊楠",
				sitenick: "小窝",
				title: "鹊楠の小窝",
				desc: "世界那么大，我想去看看",
				link: "https://blog.quenan.cn/",
				feed: "https://blog.quenan.cn/atom.xml",
				icon: "https://pic1.imgdb.cn/item/6900c4b13203f7be00ac9ded.png",
				avatar: "https://i.p-i.vip/43/20240913-66e403f2331ec.webp",
				archs: ["Nuxt", "Vercel"],
				date: "2024-10-22",
				comment: "学生，技术分享。",
			},
			{
				author: "唤青",
				sitenick: "Abloom",
				title: "唤青映记",
				desc: "Per aspera ad astra",
				link: "https://eees.blog/",
				feed: "https://eees.blog/atom.xml",
				icon: getGithubIcon("abloom25"),
				avatar: getGithubAvatar("abloom25"),
				archs: ["Nuxt", "Cloudflare"],
				date: "2024-12-09",
				comment: "高中生，技术学习中。",
			},
			{
				author: "Mugzx",
				title: "Mugzx's Blog",
				desc: "向上革命，向下实践。",
				link: "https://blog.mugzx.top/",
				feed: "https://blog.mugzx.top/atom.xml",
				icon: "https://www.mugzx.top/api/icon.png",
				avatar: "https://www.mugzx.top/api/avatar.png",
				archs: ["Nuxt", "Vercel"],
				date: "2025-01-29",
				comment: "思考博客与技术观建设。",
			},
			{
				author: "Mikuの鬆",
				sitenick: "极光星",
				title: "Mikuの极光星",
				desc: "心有多宽，世界就有多远",
				link: "https://blog.sotkg.com/",
				feed: "https://blog.sotkg.com/atom.xml",
				icon: "https://cn.cravatar.com/avatar/1012bf78fb01d5b964c3a9a0f515911a.png",
				avatar:
					"https://cn.cravatar.com/avatar/1012bf78fb01d5b964c3a9a0f515911a.png",
				archs: ["Nuxt", "EdgeOne"],
				date: "2025-03-22",
				comment: "动漫文化与自部署技术的碰撞。",
			},
			{
				author: "东方月初",
				sitenick: "BiuXin",
				title: "BiuXin-s Blog",
				desc: "人生的每一天，都在学习当中",
				link: "https://zhilu.biuxin.com/",
				feed: "https://zhilu.biuxin.com/atom.xml",
				icon: "https://x.xinb.de/i/2024/09/19/040857.webp",
				avatar: getGithubAvatar("damizai"),
				archs: ["Nuxt", "国内 CDN"],
				date: "2025-05-09",
				comment: "软件工具资源，博客部署美化。",
			},
			{
				author: "Shenley",
				sitenick: "存档点",
				title: "Shenley的存档点",
				desc: "随手存个档～",
				link: "https://blog.shenley.cn/",
				feed: "https://blog.shenley.cn/atom.xml",
				icon: "https://blog.shenley.cn/avatar.jpg",
				avatar: "https://blog.shenley.cn/avatar.jpg",
				archs: ["Nuxt", "Vercel"],
				date: "2025-05-20",
				comment: "前端开发、生活分享。",
			},
			{
				author: "液泡",
				sitenick: "部落格",
				title: "液泡部落格",
				desc: "一介书生，三尺微命",
				link: "https://blog.vacu.top/",
				feed: "https://blog.vacu.top/atom.xml",
				icon: "https://blog.vacu.top/assets/favicon.ico",
				avatar: "https://s2.loli.net/2025/08/05/vW2pnGsJOAd6qEX.jpg",
				archs: ["Nuxt", "Cloudflare"],
				date: "2025-07-26",
				comment: "对世界的学习与思考。",
			},
			{
				author: "月空人",
				desc: "偶尔写些博客，发发牢骚",
				link: "https://www.weilog.me/",
				feed: "https://www.weilog.me/atom.xml",
				icon: "https://www.weilog.me/favicon.ico",
				avatar: "https://bitmc.uno/picgo/126662463_p2.jpg",
				archs: ["Nuxt", "服务器"],
				date: "2025-07-28",
				comment: "前端大手子，运营prop.show播客，分享前端技术的心得。",
			},
			{
				author: "落憾",
				sitenick: "EnLtLH",
				title: "落憾",
				desc: "建此博客，以示吾思。话天篆地，自由吾心。",
				link: "https://blog.luoh.org/",
				feed: "https://blog.luoh.org/atom.xml",
				icon: "https://cdn2.elh.dpdns.org/picture/2025/5223b2101b56608abd83b63642984b1f.avif",
				avatar:
					"https://cdn2.elh.dpdns.org/picture/2025/57bd486ead4f5b34a28aea7f160a70ae.avif",
				archs: ["Nuxt", "Vercel"],
				date: "2025-08-17",
				comment: "中学生，以诗词、杂记等形式记录感悟与创作。",
			},
			{
				author: "AirTouch",
				desc: "分享技术、生活、思考。",
				link: "https://www.xsl.im/",
				feed: "https://www.xsl.im/atom.xml",
				icon: "https://www.xsl.im/favicon.webp",
				avatar: "https://www.xsl.im/avatar.webp",
				archs: ["Hexo", "Vercel"],
				date: "2025-08-18",
				comment:
					"网站反代配置、服务器评测、域名更换、存储加速、工具推荐、编程题解等折腾与技术分享。",
			},
			{
				author: "筱序二十",
				sitenick: "青序栈",
				desc: "青序成栈·向简而生",
				link: "https://www.qixz.cn/",
				feed: "https://www.qixz.cn/feed/",
				icon: "https://www.qixz.cn/favicon.svg",
				avatar: "https://www.qixz.cn/avatar.avif",
				archs: ["Nuxt", "Cloudflare"],
				date: "2025-08-20",
				comment: "网站攻击处理曝光，博客配置魔改等技术教程与资源分享。",
			},
			{
				author: "落尘up",
				desc: "愿你我都做,生活的高手。",
				link: "https://www.luochen.chat/",
				feed: "https://www.luochen.chat/atom.xml",
				icon: "https://www.luochenup.xyz/b_a5a3aa888355bdc617dca021efb19ab8.png",
				avatar:
					"https://www.luochenup.xyz/b_a5a3aa888355bdc617dca021efb19ab8.png",
				archs: ["Nuxt", "Vercel"],
				date: "2025-08-28",
				comment: "前端与技术入门。",
			},
			{
				author: "克喵",
				sitenick: "喵落阁",
				title: "喵落阁",
				desc: "愿你看清一切真相后，依旧热爱你的家人和朋友。",
				link: "https://blog-v3.kemeow.top/",
				feed: "https://blog-v3.kemeow.top/atom.xml",
				icon: "https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp",
				avatar:
					"https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp",
				archs: ["Nuxt", "Vercel"],
				date: "2025-09-11",
				comment: "博客折腾记录、工具/资源网站收集。",
			},
			{
				author: "fishcpy",
				sitenick: "小破站",
				title: "fishcpy的小破站",
				desc: "非淡泊无以明志，非宁静无以致远",
				link: "https://blog.fis.ink/",
				feed: "https://blog.fis.ink/atom.xml",
				icon: "https://www.fis.ink/img/logo_c.png",
				avatar: "https://www.fis.ink/img/logo.png",
				archs: ["Nuxt", "EdgeOne"],
				date: "2025-09-13",
				comment: "博客/服务器技术实践、生活记录、资源分享。",
			},
			{
				author: "Cталин",
				desc: "未觉池塘春草梦，阶前梧叶已秋声",
				link: "https://blog.jiclub.site/",
				feed: "https://blog.jiclub.site/atom.xml",
				icon: "https://m4.publicimg.browser.qq.com/publicimg/nav/qbtool/qbtool-latest.png",
				avatar: getOicqAvatar("1545433540"),
				archs: ["Nuxt", "EdgeOne"],
				date: "2025-10-12",
				comment: "情绪记录与表达。",
			},
			{
				author: "栖童",
				title: "栖童の小站",
				desc: "越努力,越幸运",
				link: "https://blog.linux-qitong.top/",
				feed: "https://blog.linux-qitong.top/atom.xml",
				icon: "https://blog.linux-qitong.top/img/favicon.webp",
				avatar: "https://blog.linux-qitong.top/img/avatar.webp",
				archs: ["Nuxt", "国内 CDN"],
				date: "2025-10-17",
				comment: "原名青稚，博客记录Linux使用、博客部署、生活反思。",
			},
			{
				author: "墨韵云阁",
				desc: "记录零散思路与技术点滴，在代码与日常间缓慢积累。偶作深思，闲时随笔，只为给此刻留下一点痕迹🪵",
				link: "https://luoyuanxiang.top/",
				feed: "https://luoyuanxiang.top/atom.xml",
				icon: "https://cdn.luoyuanxiang.top/moyunyunge-logo.png",
				avatar: "https://cdn.luoyuanxiang.top/avatar.png",
				archs: ["Nuxt", "国内 CDN"],
				date: "2025-11-04",
				comment: "后端与运维笔记。",
			},
			{
				author: "Lyi.",
				title: "凌梦望初晓",
				desc: "在无尽的绝望中前行...",
				link: "https://blog.lyi.moe/",
				icon: "https://i.lyi.moe/avatar",
				avatar: "https://i.lyi.moe/avatar",
				date: "2025-12-15",
				archs: ["Nuxt", "Cloudflare"],
				feed: "https://blog.lyi.moe/atom.xml",
				comment: "博客目前还没有文章。",
			},
		],
	},
	// #endregion
	// #region 网上邻居 since 2024
	{
		name: "网上邻居",
		desc: "哔——啵——电波通讯中，欢迎常来串门。",
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: "柳上川",
				title: "柳上川",
				desc: "宁可清贫自乐, 不作浊富多忧",
				link: "https://kawayww.com/images/blog/avatar.avif",
				icon: "https://kawayww.com/images/blog/avatar.avif",
				avatar: "https://kawayww.com/images/blog/avatar.avif",
				date: "2026-03-01",
			},
			{
				author: "LunaRain_079",
				sitenick: "寒蝉_Official",
				title: "Lunarain_079's Inn",
				desc: "暂伴月将影，行乐须及春",
				link: "https://www.lunarain.top",
				icon: "https://www.lunarain.top/favicon/favicon.ico",
				avatar: "https://avatars.githubusercontent.com/u/176664901?v=4",
				date: "2026-03-01",
			},
			{
				author: "寒冰是喵喵",
				sitenick: "寒冰",
				title: "🐱寒冰是喵喵",
				desc: "🍀 这里是寒冰，很高兴认识你！",
				link: "https://blog.hanbings.io",
				icon: "https://blog.hanbings.io/img/avatar.jpg",
				avatar: "https://blog.hanbings.io/img/avatar.jpg",
				date: "2026-03-01",
			},
			{
				author: "NolanHo",
				sitenick: "Nolan",
				title: "NolanHo",
				desc: "踏星穷极真理，长夜孤征，璀璨星河失色",
				link: "https://axi.moe",
				icon: "https://axi.moe/assets/icon.jpg",
				avatar: "https://axi.moe/assets/icon.jpg",
				date: "2026-03-01",
				comment: "是群神棍, 病娇爱好者",
			},
			{
				author: "CAICAIIs",
				sitenick: "彩彩",
				title: "CAICAIIs",
				link: "caicaiis.cc",
				icon: "https://caicaiis.cc/favicon.ico",
				avatar: "https://caicaiis.cc/assets/images/photo.jpg",
				date: "2026-03-01",
				comment: "是群外交大臣",
			},

			/* ========从此处新增友链======== */
		],
	},
	// #endregion
	// #region XUPTers
	{
		name: "XUPTers",
		desc: "西安邮电大学的校友们。",
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: "半岛的孤城",
				sitenick: "小屋",
				title: "半岛的小屋",
				desc: "不知道写啥，那就不写了。哎嘿",
				link: "https://www.bandao.ltd/",
				feed: "https://www.bandao.ltd/atom.xml",
				icon: getGithubIcon("bandaoworld"),
				avatar: getGithubAvatar("bandaoworld"),
				archs: ["Hexo", "服务器"],
				date: "2024-02-02",
				comment: "大学学长，爱好摄影/听歌，会一些Vue。",
			},
			{
				author: "学习爱我",
				sitenick: "Studio",
				title: "StudyingLover's Blog",
				desc: "要偷偷努力，下回惊艳所有人",
				link: "https://www.studyinglover.com/",
				feed: "https://www.studyinglover.com/rss.xml",
				icon: getGithubIcon("StudyingLover"),
				avatar: getGithubAvatar("StudyingLover"),
				archs: ["Astro", "Vercel"],
				date: "2024-02-03",
				comment: "“学习哥”",
			},
			{
				author: "Yuanfang",
				title: "元芳你怎么看",
				desc: "琼楼挂月钓流云，梦里瑶台暂借春",
				link: "https://yuanfang.thisis.host/",
				icon: "https://yuanfang.thisis.host/images/logo.svg",
				avatar: getGithubAvatar("zhendewokusi"),
				archs: ["Hexo", "Netlify"],
				date: "2024-02-06",
				comment: "大学同级，Linux内核学习中。",
			},
			{
				author: "Ph0m",
				sitenick: "Space",
				title: "Ph0m's space",
				desc: "好好生活 慢慢相遇",
				link: "https://blog.phom.space/",
				feed: "https://blog.phom.space/atom.xml",
				icon: getGithubIcon("Ph0m1"),
				avatar: "https://pic.imgdb.cn/item/65e1df0c9f345e8d03bcdd6a.png",
				archs: ["Hexo", "Netlify"],
				date: "2024-03-02",
				comment: "大学学弟。",
			},
			{
				author: "Future",
				title: "future's blog",
				desc: "Hang on to your dreams!",
				link: "https://future.thisis.host/",
				feed: "https://future.thisis.host/atom.xml",
				icon: "https://future.thisis.host/images/favicon-light-32.png",
				avatar: getGithubAvatar("SIMple-lives"),
				archs: ["Hexo", "Cloudflare"],
				date: "2024-03-10",
				comment: "大学学弟。",
			},
			{
				author: "tiny-sky",
				title: "tiny-sky的个人博客",
				desc: "人生苦短，及时行乐",
				link: "https://tiny-sky.github.io/",
				icon: "https://tiny-sky.github.io/img/pwa/favicon.ico",
				avatar: getGithubAvatar("tiny-sky"),
				archs: ["Hexo", "GitHub Pages"],
				date: "2024-04-03",
				comment: "大学同级，数据库学习中。",
			},
			{
				author: "Shawn",
				sitenick: "笔记",
				title: "Shawn的笔记",
				desc: "Where there is a will, there is a way.",
				link: "https://shawn.thisis.host/",
				feed: "https://shawn.thisis.host/atom.xml",
				icon: getGithubIcon("ShawnJeffersonWang"),
				avatar: getGithubAvatar("ShawnJeffersonWang"),
				archs: ["Hexo", "Cloudflare"],
				date: "2024-06-13",
				comment: "大学同级，Golang 学习中。",
			},
			// {
			// 	author: 'Kayle',
			// 	sitenick: '小站',
			// 	title: 'Kayle小站',
			// 	desc: '正在学习嵌入式',
			// 	link: 'https://www.kayle7.top/',
			// 	feed: 'https://www.kayle7.top/atom.xml',
			// 	icon: getOicqAvatar('1239625475', OicqAvatarSize.Size100),
			// 	avatar: getOicqAvatar('1239625475'),
			// 	archs: ['Hexo', 'Cloudflare'],
			// 	date: '2024-06-27',
			// 	comment: '大学同级，嵌入式学习中。',
			// 	error: '域名过期',
			// },
			// {
			// 	author: '桃林饮酒',
			// 	title: '摆烂的桃的Blog',
			// 	desc: '回不去的何止时间',
			// 	link: 'https://www.taolin.site/',
			// 	feed: 'https://www.taolin.site/rss.xml',
			// 	icon: 'https://www.taolin.site/favicon.ico',
			// 	avatar: getGithubAvatar('Taolinyinjiu'),
			// 	archs: ['Astro', 'Vercel'],
			// 	date: '2024-07-16',
			// 	comment: '大学同级，嵌入式学习中。',
			// 	error: '域名过期',
			// },
			{
				author: "Magic462",
				title: "MagicBlog",
				desc: "我知我喜乐，纵情跋涉。",
				link: "https://magic.thisis.host/",
				feed: "https://magic.thisis.host/atom.xml",
				icon: getOicqAvatar("1623728267", OicqAvatarSize.Size100),
				avatar: getOicqAvatar("1623728267"),
				archs: ["Hexo", "Cloudflare"],
				date: "2024-07-22",
				comment: "大学学妹，前端学习中。",
			},
			{
				author: "fault123",
				title: "fault`s blog",
				desc: "学习！学习！还是学习！当然也是要吃点好东西！",
				link: "https://fault.thisis.host/",
				feed: "https://fault.thisis.host/atom.xml",
				icon: getGithubIcon("fault123"),
				avatar: getGithubAvatar("fault123"),
				archs: ["Hexo", "Netlify"],
				date: "2024-07-29",
				comment: "大学同级，网安学习中。",
			},
			{
				author: "Monoceros406",
				title: "The Blog of Monoceros406",
				desc: "Reverse - 智邮普创工作室安全组/Nepnep联合战队",
				link: "https://monoceros406.github.io/",
				feed: "https://monoceros406.github.io/atom.xml",
				icon: getGithubIcon("Monoceros406"),
				avatar: getGithubAvatar("Monoceros406"),
				archs: ["Hexo", "GitHub Pages"],
				date: "2024-07-29",
				comment: "大学学弟，网安Reverse学习中。",
			},
			{
				author: "云间世界",
				title: "云间的小小世界",
				desc: "顺着风的方向",
				link: "https://yunjianworld.fun/",
				feed: "https://yunjianworld.fun/atom.xml",
				icon: "https://yunjianworld.fun/img/fluid.png",
				avatar: getOicqAvatar("2098600899"),
				archs: ["Hexo", "Cloudflare"],
				date: "2024-11-14",
				comment: "大学学妹，操作系统学习中。",
			},
			{
				author: "更多→",
				sitenick: "西邮Wiki",
				title: "西邮校友博客索引",
				desc: "西安邮电大学非官方校园生活指南",
				link: "https://wiki.cooo.site/blog",
				icon: "https://wiki.cooo.site/logo.svg",
				avatar: getGithubAvatar("xupt-wiki"),
				archs: ["VitePress", "EdgeOne"],
				date: "2025-03-27",
				comment: "我和校友建立的校园Wiki，博客索引页面收录了校友博客。",
			},
		],
	},
	// #endregion
	// #region 知识分享
	{
		name: "知识分享",
		desc: "“AI时代”创作分享/知识内容收集。",
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: "茂茂物语",
				desc: "茂茂的成长之路，包含前端常用知识、源码阅读笔记、各种奇淫技巧、日常提效工具等",
				link: "https://notes.fe-mm.com/",
				icon: getGithubIcon("maomao1996"),
				avatar: getGithubAvatar("maomao1996"),
				archs: ["VitePress", "Cloudflare"],
				date: "2024-02-17",
				comment: "前端开发笔记。",
			},
			{
				author: "石头",
				sitenick: "铭心石刻",
				title: "铭心石刻",
				desc: "愿岁并谢，与友长兮",
				link: "https://blog.kouseki.cn/",
				feed: "https://blog.kouseki.cn/rss.xml",
				icon: "https://blog.kouseki.cn/favicon.ico",
				avatar: "https://blog.kouseki.cn/imgs/avatar.webp",
				archs: ["Hexo", "Vercel"],
				date: "2024-03-01",
				comment: "折腾Hexo博客，友链页面蛮多博客折腾选手的。",
			},
			{
				author: "浪海导航",
				desc: "收录各种类型的博客以及论坛网站",
				link: "https://www.langhai.net/",
				icon: "https://www.langhai.net/assets/images/langhai-logo.png",
				avatar: "https://www.langhai.net/assets/images/langhai-logo.png",
				archs: ["Hugo", "Cloudflare"],
				date: "2024-06-04",
			},
			{
				author: "十玖八柒",
				sitenick: "Z次元",
				desc: "探索代码的世界，追寻生活的诗篇",
				link: "https://blog.ahzoo.cn/",
				feed: "https://blog.ahzoo.cn/rss.xml",
				icon: "https://blog.ahzoo.cn/favicon.ico",
				avatar: "https://ahzoo.cn/img/avatar.webp",
				archs: ["Nuxt", "服务器"],
				date: "2024-08-02",
				comment: "Nuxt博客，技术笔记。",
			},
			{
				author: "徐徐爱coding",
				desc: "一个精美的个人博客，记录平时的学习笔记",
				link: "https://www.xu69.com/",
				// feed: 'https://www.xu69.com/rss.xml',
				icon: "https://www.xu69.com/xu-resource/ico.png",
				avatar: getGithubAvatar("junxu821"),
				archs: ["Next.js", "服务器"],
				date: "2024-09-01",
				comment: "前端技术笔记，希望能做好响应式。",
				error: "2025年10月起无法访问（Connection closed）",
			},
			{
				author: "菜园前端",
				desc: "前端学习笔记分享、小白都能看懂的笔记",
				link: "https://note.noxussj.top/?s=y9",
				icon: "https://note.noxussj.top/logo.png",
				avatar: getGithubAvatar("noxussj2"),
				archs: ["VitePress", "服务器"],
				date: "2024-10-23",
				comment: "前端学习笔记。",
				// error: '2024年12月起无法访问 (504)',
			},
			{
				author: "AiQiji·工具箱",
				desc: "为开发者、设计师和效率工具爱好者精心收集的工具导航站点。让工作更高效，让创作更便捷。",
				link: "https://tools.aiqji.com/",
				icon: "https://tools.aiqji.com/favicon.ico",
				avatar: "https://tools.aiqji.com/favicon.ico",
				archs: ["React", "Cloudflare"],
				date: "2024-11-13",
				error: "内容无法访问 (接口502)",
			},
			{
				author: "阿呆",
				title: "阿呆的博客",
				desc: "分享，学习有趣的知识",
				link: "https://adaiblog.github.io/",
				feed: "https://adaiblog.github.io/atom.xml",
				icon: "https://adaiblog.github.io/favicon.ico", // expected
				avatar: "https://adaiblog.github.io/img/adai.png",
				archs: ["Hexo", "GitHub Pages"],
				date: "2025-03-11",
				comment: "技术分享与生活。",
			},
			{
				author: "iFluxArt",
				desc: "斐启智境 · 流韵新生",
				link: "https://www.iflux.art/",
				icon: "https://www.iflux.art/favicon.ico",
				avatar: "https://www.iflux.art/favicon.ico",
				archs: ["Next.js", "Vercel"],
				date: "2025-04-16",
				comment: "AI时代数字花园，含AIGC、开发、设计、运营、传媒、工具等内容。",
			},
			{
				author: "大马数字生活",
				title: "大马数字生活-digital life my",
				desc: "本部落格是一个专门分享生活在马来西亚，有关数字生活的内容包含：生活方式 个人经历 使用体验 评测分析 数码产品 分享内容 海外消费 海外通讯等内容。",
				link: "https://digitallife.my/",
				feed: "https://digitallife.my/feed/",
				icon: "https://digitallife.my/favicon.ico",
				avatar:
					"https://digitallife.my/wp-content/uploads/2025/06/cropped-1751133864-bloglogo.jpg",
				archs: ["WordPress", "Cloudflare"],
				date: "2025-06-29",
				comment: "大马数字生活及相关海外账户等事宜。",
				// TODO 2026-02-23 Cloudflare Host Error
			},
			{
				author: "硅基漫游指南",
				desc: "等待和犹豫才是这个世界上最无情的杀手",
				link: "https://blog.helong.online/",
				feed: "https://blog.helong.online/atom.xml",
				icon: "https://blog.helong.online/favicon.ico",
				avatar: "https://oss.helong.online/bucket-IMG/avatar.png",
				archs: ["Nuxt", "国内 CDN"],
				date: "2025-09-06",
				comment: "运维笔记与经验分享。",
			},
			{
				author: "墨韵先知",
				desc: "柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜",
				link: "https://www.htmacg.cn/",
				feed: "https://www.htmacg.cn/feed",
				icon: "https://www.htmacg.cn/wp-content/uploads/2025/09/cropped-RC-LOGO_icon-32x32.png",
				avatar:
					"https://www.htmacg.cn/wp-content/uploads/2025/08/cropped-user.png",
				archs: ["WordPress", "国内 CDN"],
				date: "2025-10-27",
				comment: "原名胡桃木实验室，具有运维/系统等技术分享。",
			},
			{
				author: "猫猫博客",
				desc: "𝙄𝙩’𝙨 𝙩𝙝𝙚 𝙤𝙣𝙡𝙮 𝙉𝙀𝙀𝙏 𝙩𝙝𝙞𝙣𝙜 𝙩𝙤 𝙙𝙤…",
				link: "https://catcat.blog/",
				feed: "https://catcat.blog/rss.xml",
				icon: "https://catcat.blog/favicon/avatar-540.avif",
				avatar: "https://catcat.blog/favicon/avatar-540.avif",
				archs: ["Astro", "Cloudflare"],
				date: "2025-11-18",
				comment: "自部署服务教程。",
			},
			{
				author: "bbb-lsy07",
				desc: "科技激荡人文，洞见智慧本真。",
				link: "https://blog.tsoo.net/",
				feed: "https://blog.tsoo.net/rss.xml",
				icon: "https://blog.tsoo.net/upload/lsyb.png",
				avatar: "https://blog.tsoo.net/upload/logo.jpg",
				archs: ["Hugo", "EdgeOne"],
				date: "2025-12-07",
				comment: "建站与笔记。",
			},
			{
				author: "Honesty",
				desc: "花有重开日，人无再少年",
				link: "https://blog.hehouhui.cn/",
				feed: "https://blog.hehouhui.cn/rss/feed.xml",
				icon: "https://blog.hehouhui.cn/favicon.ico",
				avatar: "https://www.hehouhui.cn/images/avatar.jpeg",
				archs: ["NotionNext", "Netlify"],
				date: "2025-12-12",
				comment: "AI时代知识分享。",
			},
			{
				author: "故河",
				title: "Guhe Blog",
				desc: "分享技术与生活趣事",
				link: "https://blog.aevi.top/",
				feed: "https://blog.aevi.top/feed.xml",
				icon: getFavicon("blog.aevi.top", { provider: "duckduckgo" }),
				avatar: getGithubAvatar("tongzanyang"),
				archs: ["Halo", "服务器"],
				date: "2026-02-05",
				comment: "自部署服务与博客美化。",
			},
		],
	},
	// #endregion
	// #region 漫游
	{
		name: "漫游",
		desc: "网上冲浪时发现的精彩内容与常读订阅，与君共享。",
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: "风记星辰",
				desc: "热爱你来过的每度温暖",
				feed: "https://www.thyuu.com/feed",
				link: "https://thyuu.com/",
				icon: "https://std.thyuu.com/logo.svg",
				avatar: "https://std.thyuu.com/logo.svg",
				archs: ["WordPress", "服务器"],
				date: "2024-02-01",
			},
			{
				author: "Randwind",
				title: "Randwind's Blog",
				desc: "你可以期待太阳从东方升起，而风却随心所欲地从四面八方吹来。",
				link: "https://www.randwind.com/",
				feed: "https://randwind.com/feed.xml",
				icon: "https://wsrv.nl/?url=randwind.com/favicon.ico",
				avatar: "https://wsrv.nl/?url=randwind.com/favicon.ico",
				archs: ["Hugo", "Cloudflare"],
				date: "2024-02-03",
				comment: "一个喜欢折腾的 Web 前端开发者。2024-05-28 关闭友链功能。",
			},
			{
				author: "静かな森",
				desc: "致虚极，守静笃。",
				link: "https://innei.in/",
				feed: "https://innei.in/feed",
				icon: "https://innei.in/innei.svg",
				avatar: getGithubAvatar("Innei"),
				archs: ["Next.js", "Cloudflare"],
				date: "2024-02-13",
			},
			{
				author: "Myth",
				desc: "荒唐无聊正经有趣的大学生 | 业余 Minecraft 腐竹 | PTer",
				title: "Myth's Blog | Myth 的小站",
				link: "https://myth.cx/",
				feed: "https://myth.cx/index.xml",
				icon: "https://myth.cx/favicon.ico",
				avatar: "https://myth.cx/img/avatar_hu_a008ef868a8cf25a.png",
				archs: ["Hugo", "国内 CDN"],
				date: "2024-04-11",
			},
			{
				author: "甜鱼",
				sitenick: "Ayu",
				title: "甜鱼/Ayu",
				desc: "三脚猫多面手，努力学习世界的一切。",
				link: "https://ayu.land/",
				feed: "https://ayu.land/rss.zh.xml",
				icon: "https://ayu.land/bin/favicon.png",
				avatar: "https://ayu.land/favicon.png",
				archs: ["HTML", "Deno Deploy"],
				date: "2024-10-26",
			},
			{
				author: "Anthony Fu",
				desc: "Hey, I am Anthony Fu, a fanatical open sourceror.",
				link: "https://antfu.me/",
				feed: "https://antfu.me/feed.xml",
				icon: "https://antfu.me/favicon.svg",
				avatar: getGithubAvatar("antfu"),
				archs: ["Vue", "Netlify"],
				date: "2024-10-26",
			},
			{
				author: "無名",
				sitenick: "小栈",
				title: "無名小栈",
				desc: "分享技术与科技生活",
				link: "https://blog.imsyy.top/",
				feed: "https://blog.imsyy.top/rss.xml",
				icon: getFavicon("blog.imsyy.top"),
				avatar: getGithubAvatar("imsyy"),
				archs: ["VitePress", "Vercel"],
				date: "2024-10-26",
			},
			{
				author: "汐笺",
				sitenick: "最小可读",
				desc: "基本无害，可能有用",
				link: "https://mvread.blog/",
				feed: "https://mvread.blog/feed",
				icon: "https://wsrv.nl/?url=mmbiz.qpic.cn/mmbiz_png/ObdOUIBwLwlt7jrOzKib6gUM83iaY6d6qLF4fH7AtAyL8mnic0jPicnFLdjXnduL5Pkj8Viah8RJAZzPwOWlj8995Qw/0",
				avatar:
					"https://cdnv2.ruguoapp.com/FufBpXB3Ax66mh9vkBEjTujMVLmPv3.jpg?imageMogr2/auto-orient/heic-exif/1/format/jpeg/thumbnail/!300x300r/gravity/Center/crop/!300x300a0a0",
				archs: ["WordPress", "Cloudflare"],
				date: "2024-10-29",
			},
			{
				author: "PlatyHsu",
				sitenick: "neverland",
				desc: "Editor. Currently at SSPAI.",
				link: "https://hsu.cy/",
				feed: "https://hsu.cy/feed.xml",
				icon: getFavicon("hsu.cy"),
				avatar:
					"https://cdnfile.sspai.com/2024/01/19/2e1141e8de2022c94ea9dd8b805f877c.png?imageMogr2/auto-orient/thumbnail/!200x200r/gravity/center/crop/200x200/format/webp/ignore-error/1",
				archs: ["Hugo", "Cloudflare"],
				date: "2025-09-03",
				comment:
					"长期记录多领域内容，涵盖数码产品软件配置、文艺作品品论等，兼具技术实践与观点分享。",
			},
		],
	},
	// #endregion
] satisfies FeedGroup[];
